config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get 'password', to: 'passwords#edit', as: :edit_password
  patch 'password', to: 'passwords#update'

  get 'about', to: 'about#index'
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'

  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  #to do the reset itself
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'

  # OmniAuth Routes
  get '/auth/twitter/callback', to: 'omniauth_callbacks#twitter'

  resources :twitter_accounts
  resources :tweets
  
  

  # Defines the root path route ("/")
  root "main#index"
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
    
    def new
    end
    
    def create
      @user = User.find_by(email: params[:email])

      if @user.present?
        #send email     
        PasswordMailer.with(user: @user).reset.deliver_later
      end
      redirect_to root_path, notice: "If an account with that email is found, we will send a link to reset your password"
    end

    def edit
        #binding.break
        @user = User.find_signed!(params[:token], purpose: "password_reset")
    rescue ActiveSupport::MessageVerifier::InvalidSignature
        redirect_to sign_in_path, alert: "Your token has expires. Please try again"
    end
    def update
        #binding.break
        @user = User.find_signed!(params[:token], purpose: "password_reset")
        if @user.update(password_params)
          redirect_to sign_in_path, notice: "Your password was reset successfully. Pls sign in"
        else
          render :edit, status: :unprocessable_entity
        end
    end

    private
    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end
end

app/views/password_resets/edit.html.erb
<h1>Reset your password</h1>

<%= form_with model: @user, url: password_reset_edit_path(token: params[:token] ) do |form| %>
    <% if form.object.errors.any? %>
    <div class="alert alert-danger">
    <% form.object.errors.full_messages.each do |messages| %>
      <div><%= messages %></div>
    <% end %>      
    </div>
    <% end %>
    <div class="mb-3">
    <%= form.label :password, class:"form-label" %>
    <%= form.password_field :password, class:"form-control", placeholder: "password" %>
  </div>
  <div class="mb-3">
    <%= form.label :password_confirmation, class:"form-label" %>
    <%= form.password_field :password_confirmation, class:"form-control", placeholder: "password" %>
  </div>
  <div class="mb-3">
     <%= form.submit "Reset Password", class:"btn btn-primary" %>
  </div>
<% end %>

app/views/password_resets/new.html.erb
<h1>Forgot your password</h1>

<%= form_with url: password_reset_path do |form| %>
  <div class="mb-3">
    <%= form.label :email, class:"form-label" %>
    <%= form.text_field :email, class:"form-control", placeholder: "user@example.com" %>
  </div>
  <div class="mb-3">
     <%= form.submit "Reset Password", class:"btn btn-primary" %>
  </div>
<% end %>