config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get 'password', to: 'passwords#edit', as: :edit_password
  patch 'password', to: 'passwords#update'

  get 'about', to: 'about#index'
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'

  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  #to do the reset itself
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'

  # OmniAuth Routes
  get '/auth/twitter/callback', to: 'omniauth_callbacks#twitter'

  resources :twitter_accounts
  resources :tweets
  
  

  # Defines the root path route ("/")
  root "main#index"
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  belongs_to :twitter_account

  validates :body, length: { minimum: 1, maximum: 280 }
  validates :publish_at, presence: true

  after_initialize do
    self.publish_at ||= 24.hour.from_now
  end

  after_save_commit do
    if publish_at_previously_changed?
      TweetJob.set(wait_until: publish_at).perform_later(self)
    end
  end

  def published?
    tweet_id?  #con el ? me devuelve tru o false no el valor
  end

  def publish_to_twitter!
    #greet = twitter_account.client_x
    twitter_account_client = twitter_account.client
    tweet_body = {text: "#{body}"}
    tweet = twitter_account_client.post("tweets", tweet_body.to_json)
    update(tweet_id: tweet["data"]["id"])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :require_user_logged_in!
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  def index
    @tweets = Current.user.tweets
  end
  def show
  end
  def new
    @tweet = Tweet.new
  end
  def create
    #binding.break
    @tweet = Current.user.tweets.new(tweet_params)
    if @tweet.save
      redirect_to tweets_path, notice: "Tweet was scheduled successfully"
    else
      render :new, status: :unprocessable_entity
    end
  end
  def edit
  end
  def update
    if @tweet.update(tweet_params)
      redirect_to tweets_path, notice: "Tweet updated successfully"
    else
      render :edit, status: :unprocessable_entity
    end
  end
  def destroy
    #binding.break
    @tweet.destroy
    redirect_to tweets_path, notice: "Tweet was unescheduled"
  end

  private
  def tweet_params
    params.require(:tweet).permit(:twitter_account_id, :body, :publish_at)
  end
  def set_tweet
    @tweet = Current.user.tweets.find(params[:id])
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<%= form_with model: @tweet do |form| %>
  <%= render "shared/form_errors", form: form %>
  <div class="mb-3">
      <%= form.label :twitter_account_id %>
      <%= form.collection_select :twitter_account_id, Current.user.twitter_accounts, :id, :username, {}, class:"form-control"%>
      <%= link_to "Connect your twitter account", twitter_accounts_path, class:"btn btn-primary"  %>
  </div>
  <div class="mb-3">
    <%= form.label :body %>
    <%= form.text_area :body, class: "form-content" %>
  </div>
  <div class="mb-3">
    <%= form.label :publish_at %>
    <div class="class-control">
      <%= form.datetime_select :publish_at %>
    </div>
  </div>

  <%= form.button "Schedule", class: "btn btn-primary" %>

  <% if form.object.persisted? %>
    <%= link_to "Destroy", form.object, data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  }, class: "btn btn-outline-danger"  %>
  <% end %>  
<% end %>

app/views/tweets/_tweet.html.erb
<div class="mb-3 card card-body">
  <%= tweet.body %>
  <div class="me-4">
    <%= image_tag tweet.twitter_account.image, class:"rounded-circle" %>
    <%= link_to "#{tweet.twitter_account.username}", "https://twitter.com/#{tweet.twitter_account.username}", target: :_blank %>

    <% if tweet.published? %>
      <%= link_to "View tweet","https://twitter.com/#{tweet.twitter_account.username}/status/#{tweet.tweet_id}", target: :_blank %>
    <% else %>
      Schedule for <%= l tweet.publish_at, format: :short %>
      <%= link_to "Edit Tweet", edit_tweet_path(tweet) %>
    <% end%>
  </div>
</div>

app/views/tweets/edit.html.erb
<h1>Edit Scheduled Tweet</h1>

<%= render "form", tweet: @tweet %>

app/views/tweets/index.html.erb
<div class="d-flex justify-content-between align-items-center">
  <h1>Tweets</h1>
    <% if Current.user.twitter_accounts.any? %>
      <%= link_to "Schedule a Tweet", new_tweet_path, class:"btn btn-primary"  %>
    <% end %>

     <% if Current.user.twitter_accounts.none? %>
     <%= link_to "Connect your twitter account", twitter_accounts_path, class:"btn btn-primary"  %>
    <% end %>
</div>

<%= render @tweets %>

app/views/tweets/new.html.erb
<h1>Schedule a Tweet</h1>

<%= render "form", tweet: @tweet %>