config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get 'password', to: 'passwords#edit', as: :edit_password
  patch 'password', to: 'passwords#update'

  get 'about', to: 'about#index'
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'

  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  #to do the reset itself
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'

  # OmniAuth Routes
  get '/auth/twitter/callback', to: 'omniauth_callbacks#twitter'

  resources :twitter_accounts
  resources :tweets
  
  

  # Defines the root path route ("/")
  root "main#index"
end

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
    <div class="alert alert-primary at-4" role="alert">
        <%= flash.now[:notice] %>
    </div>
<% end %>
<% if flash[:alert] %>
    <div class="alert alert-warning" role="alert">
        <%= flash.now[:alert] %>
</div>
<% end %>

app/views/shared/_form_errors.html.erb
<% if form.object.errors.any? %>
 <div class="alert alert-danger">
  <% form.object.errors.full_messages.each do |messages| %>
    <div><%= messages %></div>
  <% end %>      
 </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Tweets", tweets_path, class:"nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "Twitter Accounts", twitter_accounts_path, class:"nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <% if Current.user %>
            <li class="nav-item">
              <%= link_to Current.user.email, edit_password_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
               <%= button_to "Logout", logout_path, method: :delete, class:"btn btn-outline-success"  %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Sign Up", sign_up_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign In", sign_in_path, class:"nav-link" %>
            </li>
          <% end %>
        
      </ul>
    </div>
  </div>
</nav>